// pages/nabor/helper.tsx
export default function Helper() {
  return (
    <div>
      <section id="banner" className="sm">
        <div className="pagename">
            <h1>Helper</h1>
        </div>
      </section>
      <section id="pagecontent">
        <div className="container">
          <h1 style={{textAlign: "center", fontSize: "xx-large"}}>
            <span style={{color: "#000000"}}><b>Nábor na Helpera</b></span>
          </h1>
          <h4><span style={{color: "#000000"}}>Jak se stát Helperem?</span></h4>
          <ul>
          <span style={{color: "#000000"}}>
            Pokud je zrovna otevřený formulář, tak se se svými herními údaji
            přihlásíte do{" "}
            <a href="http://info.qplay.cz/" target="_blank" rel="noreferrer"
            >Informačního Panelu</a
            >{" "}
            → kliknete na záložku &quot;Nábor na Helpera&quot; → zobrazený formulář
            vyplníte a odešlete.
          </span>
          </ul>
          <h4><span style={{color: "#000000"}}>Výhody Helpera</span></h4>
          <li>
          <span style={{color: "#000000"}}>
            Vlastní veškeré MASTER VIP výhody a vybrané LEGEND VIP výhody.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Může se připojit do plného týmu na minihře MiniAnnihilation a
            Crystals.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Jednou za měsíc může udělat svou velkou akci na Discordu, kam obdrží zdarma
            odměny do soutěže.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Může pořádat menší akce na Discordu v &quot;QPlay Stage&quot;.
          </span>
          </li>
          <br/>
          <h4><span style={{color: "#000000"}}>Odměna za práci Helpera</span></h4>
          <li>
          <span style={{color: "#000000"}}>
            Každý měsíc obdrží určitou sumu coinů za odvedenou práci v
            ticket-systému.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Za odvedenou práci obdrží každý měsíc zpravidla 1x Basic VIP.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            V závislosti na odvedené práci může každý měsíc získat navíc další
            druhy VIP.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Za odvedenou práci může každý měsíc získat navíc různé typy crates.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            V závislosti na odvedené práci může obdržet hmotný balíček.
          </span>
          </li>
          <li>
          <span style={{color: "#000000"}}>
            Po rozhodnutí vedení serveru může za svou odvedenou práci získat
            finanční odměnu.
          </span>
          </li>
        </div>
      </section>
    </div>
  )
}

// pages/nabor/helper.vue
<template>
  <div>
    <section class="wrapper style1">
      <div class="container">
        <h1 style="text-align: center; font-size: xx-large">
          <span style="color: #000000"><b>Nábor na Helpera</b></span>
        </h1>
        <h4><span style="color: #000000">Jak se stát Helperem?</span></h4>
        <ul>
          <span style="color: #000000">
            Pokud je zrovna otevřený formulář, tak se se svými herními údaji
            přihlásíte do
            <a href="http://info.qplay.cz/" target="_blank">Informačního Panelu</a> → kliknete na záložku "Nábor na Helpera" → zobrazený formulář vyplníte a
            odešlete.
          </span>
        </ul>
        <h4><span style="color: #000000">Výhody Helpera</span></h4>
        <ul>
          <li>
            <span style="color: #000000">Vlastní veškeré VIP výhody.</span>
          </li>
          <li>
            <span style="color: #000000">
              Může se připojit do plného týmu na minihře MiniAnnihilation a
              Crystals.
            </span>
          </li>
        </ul>
        <h4><span style="color: #000000">Odměna za práci Helpera</span></h4>
        <ul>
          <span style="color: #000000">
            Každý měsíc obdrží určitou sumu coinů za odvedenou práci v
            ticket-systému.
          </span>
        </ul>
        <li>
          <span style="color: #000000">
            Za odvedenou práci obdrží zpravidla 1x Basic VIP.
          </span>
        </li>
        <li>
          <span style="color: #000000">
            V závislosti na odvedené práci může každý měsíc získat navíc další
            druhy VIP.
          </span>
        </li>
        <li>
          <span style="color: #000000">
            Za odvedenou práci může každý měsíc získat navíc různé typy crates.
          </span>
        </li>
        <li>
          <span style="color: #000000">
            V závislosti na odvedené práci může obdržet hmotný balíček.
          </span>
        </li>
        <li>
          <span style="color: #000000">
            Po rozhodnutí vedení serveru může za svou odvedenou práci získat
            finanční odměnu.
          </span>
        </li>
        <li>
          <span style="color: #000000">
            Jednou za měsíc může udělat svou akci na Discordu, kam obdrží zdarma
            odměny do soutěže.
          </span>
        </li>
      </div>
    </section>
  </div>
</template>
