// pages/vip.tsx
import Head from "next/head";
import VIPTable from "../components/VIPTable";
import Banner from "../components/Banner";

export default function VIP() {
  return (
    <div>
      <Head>
        <title>VIP | QPlay.cz</title>
        <meta name="description" content="Zakoupení VIP účtu na našem serveru."/>
      </Head>
      <Banner sm={true}>
        <div className="pagename">
          <h1>VIP ÚČET</h1>
        </div>
      </Banner>
      <section className="pagecontent">
        <div className="container">
          {/* <center>
            <a href="#darkovyPoukaz" style="text-decoration:none;border:none;"
              ><img src="/images/BannerPNGFinal.png" style="max-width:100%"/></a
            ><br />
            <br />
          </center> */}
          {/*  
    <center>
            <a href="#naramekAkce" style="text-decoration:none;border:none;"><img src="images/WebNaramkyAkce.png?ver=2" ></a><br> <br><br>
    </center>    */}
          <div className="btnsgroup">
            <a className="button" href="https://kod.qplay.cz/">
              <button>AKTIVOVAT VIP KÓD</button>
            </a>
            <a className="button" href="#zakoupeniVIP">
              <button>Zakoupit VIP</button>
            </a>
          </div>
          <br/>
          {/*  <header>
            <center>
              <h2>Jak si koupit VIP?</h2>
            </center>
          </header> */}
          {/*  <h2><b><center><font color=indianred>Speciální VÁNOČNÍ Crate pro všechna VIP!</font></b></center></h2>
          <h2><b><center><font color=firebrick>SILVESTROVSKÁ  AKCE: Ke všem VIP + 1 Crate!</font></b></center></h2>
          <h2>
            <center>
              <font color="orange" style="font-weight: bold;">
                Speciální HALLOWEEN Crate pro všechna VIP!
              </font>
            </center>
          </h2> */}
          {/*  h2>
            <center>
              <font color="indianred" style="font-weight: bold">
                Pololetní akce na všechna VIP!
              </font>
            </center>
          </h2> */}
          {/* h2>
            <center>
              <font color="indianred" style="font-weight: bold">
                Speciální CHRISTMAS Crate pro všechna VIP!
              </font>
            </center>
          </h2> */}
          {/* <h2>
            <div style={{textAlign: "center"}}>
              <span style={{fontWeight: "bold", color: "#e75480"}}>
              Valentýnská akce na všechna VIP!
              </span>
            </div>
          </h2> */}
          {/* <h2>
            <div style={{textAlign: "center"}}>
              <span style={{fontWeight: "bold", color: "#2AC820"}}>
                Velikonoční akce na VIP!
              </span>
            </div>
          </h2> */}
          <h3 style={{textAlign: "center"}}>
            <span style={{fontWeight: "bold"}}>Více položek na QPlay Store! <br />
              →{" "}<a
              href="https://store.qplay.cz/category/328613" target="_blank" rel="noreferrer">store.qplay.cz</a>{" "}←</span>
          </h3>
          {/*<h4 style={{textAlign: "center"}}>
          <span><a href="#poukaz VIP" ><Image src={Voucher} /></a></span>
        </h4>*/}
          <br/>
          <div className="table-responsive">
            <VIPTable/>
          </div>
          <a id="zakoupeniVIP" style={{position: "relative", top: "-50vh"}}/>

          <br/>

          <p>
            *Crate Shards je měna, kterou vlastní pouze hráč s LEGEND VIP.
            Získává se místo Coinů hraním miniher. Na Lobby v Crate Factory si lze
            následně Crate Shards proměnit na normální crates (BASIC, MYSTERY,
            LEGEND) a v sezónách i na například Christmas, Valentine, Halloween
            crate.
          </p>

          <div>
            <h2>Jak aktivovat VIP kód?</h2>
            <p>
              Od 4.12.2017 přecházíme na nový systém aktivace VIP účtů. Zakoupíte
              si tzv. KÓD K AKTIVOVÁNÍ VIP ÚČTU - pomocí sms, PayPalu či PSC a ve
              zpětné sms obdržíte 8 místný kód ve tvaru XXXX-XXXX. Po jeho
              obdržení doporučujeme navštívit stránku
              <a href="https://kod.qplay.cz"> https://kod.qplay.cz</a>, kam kód
              zadáte a máte možnost jej aktivovat na serveru či přímo přes
              internet. Dále je také možnost vygenerovat
              <b> dárkovou poukázku - ideální dárek pro Vaše kamarády či rodinu.</b>
            </p>

            <div>
              <b>Postup:</b><br/>
              1) Zakoupíte si KÓD - standardním způsobem - SMS, PSC, PayPal<br/>
              2) Po obdržení kódu (XXXX-XXXX) přejdete na stránku
              <a href="https://kod.qplay.cz"> https://kod.qplay.cz</a>, kam kód
              zadáte<br/>
              3) Zvolíte možnost aktivace<br/>
              4) Počkáte cca 5 minut a Vaše VIP výhody by měly být aktivní!<br/>
            </div>
            <br/>
            <div>
              Případně můžete aktivovat kód na serveru příkazem na Lobby:
              <b> /kod [VAS_KOD]</b> - takže například /kod 1234-5678
            </div>
            <br/>
            <p>
              Při současně aktivovaných více druhů VIP zároveň se nejprve aktivuje
              to nejlepší a poté se postupně aktivují sestupně od nejlepších po
              nejhorší. Při zakoupení více VIP stejného typu se doby expirace
              prodlužují.
            </p>
          </div>

          <div className="href-offset">
            <span className="offset"><a id="poukaz VIP"/></span>
            <a className="darkovyPoukaz"/>
            <h2>Zakoupení dárkového poukazu na VIP</h2>
            <p>
              Sháníte dárek pro svého kamaráda, kamarádku, syna, dceru…? Dárkový
              poukaz na PREMIUM účet na herním serveru QPlay.cz jistě nebude
              špatná volba.<br/>
              <br/>
              <b>Jak to funguje?</b> <br/>
              Vyberte si jednu z možností platby: SMS, PayPal či PaySafeCard a
              postupujte dle pokynů uvedených na této stránce. Po úspěšném
              zaplacení Vám přijde sms (v případě platby pomocí sms) nebo email (v
              případě platby pomocí PSC nebo PayPal) s kódem. Tento kód zadejte na
              stránce <a href="https://kod.qplay.cz" target="_blank" rel="noreferrer">https://kod.qplay.cz</a> a zvolte
              možnost vygenerovat dárkový poukaz. Tento vygenerovaný
              dárkový poukaz je možné vytisknout a je platný ihned po
              zaplacení.<br/><br/>
              V případě jakýchkoliv dotazů se na nás neváhejte obrátit – jak se
              dozvíte v sekci Kontakt.
            </p>

            <div>
              Další informace k VIP platbě, <em>reklamace</em> atd. můžete řešit
              pomocí ticketu na
              <a href="https://info.qplay.cz"><strong> info.qplay.cz</strong></a>
              , případně napište na email: <strong>support@qplay.cz</strong>,
              Děkujeme
            </div>
          </div>

          <div style={{marginTop: "2em"}}>
            <h2>Máte problém s VIP?</h2>
            <ol style={{listStyle: "decimal", listStylePosition: "inside"}}>
              <li>VIP se vám na serveru aktivuje obvykle do 5 minut</li>
              <li>
                Pokud VIP i po hodině od odeslání SMS nemáte, zkontrolujte si text
                a číslo SMS, kterou jste odeslal/a a zda vám byla doručena
                potvrzovací zpráva o provedení platby
              </li>
              <li>
                V případě, že neshledáte chybu na své straně, napište ticket na
                <a href="https://info.qplay.cz" style={{fontWeight: "bold"}}
                > info.qplay.cz </a
                >
                a vše zde s vámi prověříme
              </li>
              <li>
                Odeslání SMS může blokovat nedostatečná výše kreditu či zakázané
                PREMIUM SMS platby, tyto problémy musíte vyřešit s vaším
                operátorem
              </li>
              <li>Za špatně zaslanou SMS neneseme žádnou zodpovědnost</li>
            </ol>
          </div>

          <div>
            <h2>Pravidla - VIP</h2>
            <ul>
              <li>
                VIP bude po zadání kódu aktivováno obvykle do 5 minut. Pokud ani
                po hodině nemáte VIP výhody aktivní, neváhejte se na nás obrátit.
              </li>
              <li>
                VIP neslouží jako obrana vůči banu = v případě porušení Obchodních
                podmínek, Podmínek použití služeb QPlay.cz či pravidel herního
                serveru, může Vám být zakázán přístup na server.
              </li>
              <li>Za špatně odeslanou platbu neneseme žádnou zodpovědnost.</li>
              <li>
                Zakoupením kódu k aktivaci VIP účtu souhlasíte, že rozumíte a
                souhlasíte s Obchodními podmínkami, Podmínkami použití služeb
                QPlay.cz a Pravidly herního serveru QPlay.cz a zavazujete se je
                dodržovat.
              </li>
              <li>
                Zakoupením kódu k aktivaci VIP účtu potvrzujete, že jste byli
                seznámeni s tím, že kupující nemá nárok na odstoupení od kupní
                smlouvy (do 14 dnů), jedná se o dodání digitálního obsahu bez
                hmotného nosiče.
              </li>
              <li>
                Negarantujeme, že po dobu trvání VIP výhod bude umožněn přístup na
                server. V případě, že herní server QPlay.cz nebude dále
                provozován, veškeré VIP účty a neaktivované VIP kódy s okamžitou
                platností zanikají bez nároku na finanční či jinou náhradu.
              </li>
              <li>
                Vyhrazujeme si právo na okamžitou úpravu VIP výhod bez upozornění.
              </li>
            </ul>
          </div>

          <div>
            <h2>GoPay</h2>
            <p>
              GoPay je platební brána, umožňující platbu pomocí PayPal,
              PaySafeCard, bankovním převodem (online i standardním), platební
              kartou (pouze Visa), ...
            </p>
            <div>
              <img
                src="/imgBrana/1.png"
                style={{height: "40px", marginRight: "10px"}}
              /><img
              src="/imgBrana/2.png"
              style={{height: "40px", marginRight: "10px"}}
            /><img
              src="/imgBrana/4.png"
              style={{height: "40px", marginRight: "10px"}}
            /><img
              src="/imgBrana/5.png"
              style={{height: "40px", marginRight: "10px"}}
            /><img
              src="/imgBrana/8.png"
              style={{height: "40px", marginRight: "10px"}}
            />
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

// vip.vue
<template>
  <div>
    <section class="wrapper style1" style="padding: 2em 0 1em 0">
      <div id="test" class="container">
        <!--<center>
          <a href="#darkovyPoukaz" style="text-decoration:none;border:none;"><img src="images/BannerPNGFinal.png" style="max-width:100%" ></a><br> <br><br>
  </center>-->
        <!--
  <center>
          <a href="#naramekAkce" style="text-decoration:none;border:none;"><img src="images/WebNaramkyAkce.png?ver=2" ></a><br> <br><br>
  </center>      -->

        <center>
          <a href="https://kod.qplay.cz/">
            <input
              id="aktivovatVIP"
              type="submit"
              name="submit"
              value="AKTIVOVAT VIP KÓD"
            />
          </a>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <a href="#zakoupeniVIP">
            <input
              id="souhlasPort"
              type="submit"
              name="submit"
              value="Zakoupit VIP"
            />
          </a>
        </center>
        <br />
        <header>
          <center>
            <h2>Jak si koupit VIP?</h2>
          </center>
        </header>
        <!--<h2><b><center><font color=indianred>Speciální VÁNOČNÍ Crate pro všechna VIP!</font></b></center></h2>
        <h2><b><center><font color=firebrick>SILVESTROVSKÁ AKCE: Ke všem VIP + 1 Crate!</font></b></center></h2>-->

        <div class="row 200%">
          <div class="4u 12u(narrower)">
            <div id="sidebar">
              <!-- Content -->
              <article>
                <!-- <span class="image featured"><img src="images/banner.jpg" alt="" /></span> -->
                <h2>1) BASIC</h2>
                <strong>Výhody:</strong>
                <ul style="list-style-type: disc; padding: 0px 20px 0px;">
                  <li>Připojí se na plný server i minihru!</li>
                  <li>
                    Má v chatu žlutý prefix
                    <span style="color: #ffcc00;">BASIC</span>
                  </li>
                  <li>
                    Má v tabu žlutý prefix
                    <span style="color: #ffcc00;">BASIC</span>
                  </li>
                  <b>
                    <li>
                      Dostane 10 000
                      <span style="color: red;display: none;">(6 000)</span>
                      Coinu
                    </li>
                    <li>Ve hře získává o 10% více Coinů</li>
                    <li>
                      Dostane 1
                      <span style="color: red;display: none;">(4)</span>
                      MYSTERY CRATE
                    </li>
                    <!--<li><span style="color: indianred;">Dostane 1 VÁNOČNÍ CRATE</span></li>-->
                  </b>
                  <li>Může si zrodit mazlíčka a starat se o něho.</li>
                  <li>Nepůsobí na něj SlowMode</li>
                  <li>Může psát soukromé zprávy /tell a /r</li>
                  <li>Delší čas, než budete kicknuti za AFK (5 minut)</li>
                  <li>Speciální příkaz na posílání věcí /trade nick</li>
                  <!--<li>Speciální příkaz na duel na 1vs1 /duel nick</li>-->
                  <li>2x Více coinů za strávený čas na serveru</li>
                  <li>Až <b>10</b> přátel pomocí příkazu /friend</li>
                  <li>Až <b>3</b> hráči v Party pomocí příkazu /party</li>
                  <li>Létání na Lobby pomocí příkazu /fly</li>
                  <li>Psaní barevných zpráv do chatu na Lobby</li>
                  <li>Až 18 slotů v EnderTruhle na MiniAnni</li>
                  <li>Speciální doplňky na ModernBedWars</li>
                  <li>45% daň při převodu Coinů</li>
                </ul>
                <span style="color: firebrick; font-size: 20px; ">
                  > <strong>Délka trvání výhod: </strong>30 dní (Coiny jsou
                  přičteny jednorázově)
                </span>
                <br />
                <span style="color: firebrick; font-size: 25px; ">
                  <strong>Cena: </strong>50 Kč nebo 2 € (včetně DPH)
                </span>
                <br /><br />
                <a href="https://pay.net-inout.cz/?pw=123987465&produkt=1">
                  <input
                    type="submit"
                    name="submit"
                    value="Zakoupit BASIC VIP"
                  />
                </a>
              </article>
            </div>
          </div>
          <div class="4u 12u(narrower)">
            <div id="sidebar">
              <!-- Sidebar -->
              <section>
                <h2>2) MEDIUM</h2>
                <strong>Výhody:</strong>
                <ul style="list-style-type: disc; padding: 0px 20px 0px;">
                  <li>Připojí se na plný server i minihru!</li>
                  <li>
                    Má v chatu žlutý prefix
                    <span style="color: #ffcc00;">MEDIUM</span>
                  </li>
                  <li>
                    Má v tabu žlutý prefix
                    <span style="color: #ffcc00;">MEDIUM</span>
                  </li>
                  <b>
                    <li>
                      Dostane 25 000
                      <span style="color: red;display: none;"> (6 000) </span>
                      Coinu
                    </li>
                    <li>Ve hře získává o 15% více Coinů</li>
                    <li>
                      Dostane 3
                      <span style="color: red;display: none;">(4) </span>MYSTERY
                      CRATE
                    </li>
                    <!--<li><span style="color: indianred;">Dostane 2 VÁNOČNÍ CRATE</span></li>-->
                  </b>
                  <li>Může si zrodit mazlíčka a starat se o něho.</li>
                  <li>Nepůsobí na něj SlowMode</li>
                  <li>Může psát soukromé zprávy /tell a /r</li>
                  <li>Delší čas, než budete kicknuti za AFK (5 minut)</li>
                  <li>Speciální příkaz na posílání věcí /trade nick</li>
                  <!--<li>Speciální příkaz na duel na 1vs1 /duel nick</li>-->
                  <li>2x Více coinů za strávený čas na serveru</li>
                  <li>Až <b>10</b> přátel pomocí příkazu /friend</li>
                  <li>Až <b>4</b> hráči v Party pomocí příkazu /party</li>
                  <li>Létání na Lobby pomocí příkazu /fly</li>
                  <li>Psaní barevných zpráv do chatu na Lobby</li>
                  <li>Až 18 slotů v EnderTruhle na MiniAnni</li>
                  <li>Speciální doplňky na ModernBedWars</li>
                  <li>40% daň při převodu Coinů</li>
                </ul>
                <span style="color: firebrick; font-size: 20px; ">
                  <strong>Délka trvání výhod: </strong>30 dní (Coiny jsou
                  přičteny jednorázově)
                </span>
                <br />
                <span style="color: firebrick; font-size: 25px; ">
                  <strong>Cena: </strong>99 Kč nebo 4 € (včetně DPH)
                </span>
                <br /><br />
                <a href="https://pay.net-inout.cz/?pw=123987465&produkt=2">
                  <input
                    type="submit"
                    name="submit"
                    value="Zakoupit MEDIUM VIP"
                  />
                </a>
              </section>
            </div>
          </div>
          <div class="4u 12u(narrower)">
            <div id="sidebar">
              <!-- Sidebar -->
              <section>
                <h2>3) MASTER</h2>
                <strong>Výhody:</strong>
                <ul style="list-style-type: disc; padding: 0px 20px 0px;">
                  <li>Připojí se na plný server i minihru!</li>
                  <li>
                    Má v chatu žlutý prefix
                    <span style="color: #ffcc00;">MASTER</span>
                  </li>
                  <li>
                    Má v tabu žlutý prefix
                    <span style="color: #ffcc00;">MASTER</span>
                  </li>
                  <b>
                    <li>Dostane 50 000 Coinu</li>
                    <li>Ve hře získává o 20% více Coinů</li>
                    <li>Dostane 6 MYSTERY CRATE</li>
                    <!--<li><span style="color: indianred;">Dostane 3 VÁNOČNÍ CRATE</span></li>-->
                  </b>
                  <li>Může si zrodit mazlíčka a starat se o něho.</li>
                  <li>Může si svého mazlíčka pojmenovat.</li>
                  <li>Má možnost automatického přijímání úkolů na SkyWars.</li>
                  <li>Nepůsobí na něj SlowMode</li>
                  <li>Může psát soukromé zprávy /tell a /r</li>
                  <li>Delší čas, než budete kicknuti za AFK (5 minut)</li>
                  <li>Speciální příkaz na posílání věcí /trade nick</li>
                  <!--<li>Speciální příkaz na duel na 1vs1 /duel nick</li>-->
                  <li>2x Více coinů za strávený čas na serveru</li>
                  <li>Až <b>10</b> přátel pomocí příkazu /friend</li>
                  <li>Až <b>5</b> hráčů v Party pomocí příkazu /party</li>
                  <li>Létání na Lobby pomocí příkazu /fly</li>
                  <li>Psaní barevných zpráv do chatu na Lobby</li>
                  <li>Až 18 slotů v EnderTruhle na MiniAnni</li>
                  <li>Speciální doplňky na ModernBedWars</li>
                  <li>35% daň při převodu Coinů</li>
                </ul>
                <span style="color: firebrick; font-size: 20px; ">
                  <strong>Délka trvání výhod: </strong>30 dní (Coiny jsou
                  přičteny jednorázově)
                </span>
                <br />
                <span style="color: firebrick; font-size: 25px; ">
                  <strong>Cena: </strong>189 Kč nebo 7,5 € (včetně DPH)
                </span>
                <br /><br />
                <a href="https://pay.net-inout.cz/?pw=123987465&produkt=3">
                  <input
                    type="submit"
                    name="submit"
                    value="Zakoupit MASTER VIP"
                  />
                </a>
              </section>
            </div>
          </div>
        </div>
        <A n-a-m-e="zakoupeniVIP"></A>

        <br /><br /><br />

        <br />
        <br />
        <h2>Jak aktivovat VIP kód?</h2>
        <p>
          Od 4.12.2017 přecházíme na nový systém aktivace VIP účtů. Zakoupíte si
          tzv. KÓD K AKTIVOVÁNÍ VIP ÚČTU - pomocí sms, PayPalu či PSC a ve
          zpětné sms obdržíte 8 místný kód ve tvaru XXXX-XXXX. Po jeho obdržení
          doporučujeme navštívit stránku
          <a href="https://kod.qplay.cz">https://kod.qplay.cz</a>, kam kód
          zadáte a máte možnost jej aktivovat na serveru či přímo přes internet.
          Dále je také možnost vygenerovat
          <b>dárkovou poukázku - ideální dárek pro Vaše kamarády či rodinu.</b>
        </p>
        <b>Postup:</b><br />
        1) Zakoupíte si KÓD - standardním způsobem - SMS, PSC, PayPal<br />
        2) Po obdržení kódu (XXXX-XXXX) přejdete na stránku
        <a href="https://kod.qplay.cz">https://kod.qplay.cz</a>, kam kód
        zadáte<br />
        3) Zvolíte možnost aktivace<br />
        4) Počkáte cca 5 minut a Vaše VIP výhody by měly být aktivní!<br />

        <br />
        Případně můžete aktivovat kód na serveru příkazem na Lobby:
        <b>/kod [VAS_KOD]</b> - takže například /kod 1234-5678

        <br />
        <br />
        <h2 style="margin-bottom: 0px">
          GoPay
        </h2>
        GoPay je platební brána, umožňující platbu pomocí PayPal, PaySafeCard,
        bankovním převodem (online i standardním), platební kartou...
        <br /><br />
        <div>
          <img
            src="/imgBrana/1.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/2.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/3.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/4.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/5.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/6.png"
            style="height:40px;margin-right:10px"
          /><img
            src="/imgBrana/7.png"
            style="height:40px;margin-right:10px"
          /><img src="/imgBrana/8.png" style="height:40px;margin-right:10px" />
        </div>

        <hr />

        <div>
          <A n-a-m-e="darkovyPoukaz"></A>
          <h2 style="margin-bottom: 0px">
            Zakoupení dárkového poukazu na VIP
          </h2>
          <p>
            Sháníte dárek pro svého kamaráda, kamarádku, syna, dceru…? Dárkový
            poukaz na PREMIUM účet na herním serveru QPlay.cz jistě nebude
            špatná volba.<br />
            <br />
            <b>Jak to funguje?</b> <br />
            Vyberte si jednu z možností platby: SMS, PayPal či PaySafeCard a
            postupujte dle pokynů uvedených na této stránce. Po úspěšném
            zaplacení Vám přijde sms (v případě platby pomocí sms) nebo email (v
            případě platby pomocí PSC nebo PayPal) s kódem. Tento kód zadejte na
            stránce
            <a href="https://kod.qplay.cz" target="_blank">
              https://kod.qplay.cz
            </a>
            a zvolte možnost vygenerovat dárkový poukaz. Tento vygenerovaný
            dárkový poukaz je možné vytisknout a je platný ihned po
            zaplacení.<br /><br />
            V případě jakýchkoliv dotazů se na nás neváhejte obrátit – jak se
            dozvíte v sekci Kontakt.
          </p>
        </div>
        <br />
        Další informace k VIP platbě, <em>reklamace</em> atd. můžete řešit
        pomocí ticketu na
        <a href="https://info.qplay.cz"><strong>info.qplay.cz</strong></a>
        , případně napište na email: <strong>qplay@net-inout.cz</strong>,
        Děkujeme<br />
        <hr />
        <h2>Máte problém s VIP?</h2>
        <b>1.</b> VIP se vám na serveru aktivuje obvykle do 5 minut<br />
        <b>2.</b> Pokud VIP i po hodině od odeslání SMS nemáte, zkontrolujte si
        text a číslo SMS, kterou jste odeslal/a a zda vám byla doručena
        potvrzovací zpráva o provedení platby<br />
        <b>3.</b> V případě, že neshledáte chybu na své straně, napište ticket
        na <a href="https://info.qplay.cz"><strong>info.qplay.cz</strong></a> a
        vše zde s vámi prověříme<br />
        <b>4.</b> Odeslání SMS může blokovat nedostatečná výše kreditu či
        zakázané PREMIUM SMS platby, tyto problému musíte vyřešit s vaším
        operátorem<br />
        <b>5.</b> Za špatně zaslanou SMS neneseme žádnou zodpovědnost

        <hr />
        <h2>Pravidla - VIP</h2>
        <ul>
          <li>
            <span style="color: #000000;">
              VIP bude po zadání kódu aktivováno obvykle do 5 minut. Pokud ani
              po hodině nemáte VIP výhody aktivní, neváhejte se na nás obrátit.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              VIP neslouží jako obrana vůči banu = v případě porušení Obchodních
              podmínek, Podmínek použití služeb QPlay.cz či pravidel herního
              serveru, může Vám být zakázán přístup na server.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              Za špatně odeslanou platbu neneseme žádnou zodpovědnost.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              Zakoupením kódu k aktivaci VIP účtu souhlasíte, že rozumíte a
              souhlasíte s Obchodními podmínkami, Podmínkami použití služeb
              QPlay.cz a Pravidly herního serveru QPlay.cz a zavazujete se je
              dodržovat.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              Zakoupením kódu k aktivaci VIP účtu potvrzujete, že jste byli
              seznámeni s tím, že kupující nemá nárok na odstoupení od kupní
              smlouvy (do 14 dnů), jedná se o dodání digitálního obsahu bez
              hmotného nosiče.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              Negarantujeme, že po dobu trvání VIP výhod bude umožněn přístup na
              server. V případě, že herní server QPlay.cz nebude dále
              provozován, veškeré VIP účty a neaktivované VIP kódy s okamžitou
              platností zanikají bez nároku na finanční či jinou náhradu.
            </span>
          </li>
          <li>
            <span style="color: #000000;">
              Vyhrazujeme si právo na okamžitou úpravu VIP výhod bez upozornění.
            </span>
          </li>
        </ul>
      </div>
    </section>
  </div>
</template>
