// pages/pravidla.tsx
export default function Rules() {
  return (
    <div>
      <section className="wrapper style1">
        <div className="container">
          <h1 style={{textAlign: "center", color: "#000000"}}>
            Všeobecné obchodní podmínky a Podmínky používání služeb QPlay.cz
          </h1>
          <div style={{textAlign: "center", marginTop: "2em"}}>
            {/* <h4 style="margin-bottom: 0px;">Platné od 1.7.2020</h4>
            <div>
              Ke dni 1.7. dochází ke změně provozovatele na QPlay Network s.r.o.
            </div> */}
            <a href="/dokumenty/VOP-01-07-2020.pdf" target="_blank">
              Obchodní podmínky (VOP)
            </a>
            <br/>
            <a href="/dokumenty/PodminkyPouzivani-01-07-2020.pdf" target="_blank">
              Podmínky používání služeb QPlay.cz
            </a>
            <br/>
            <a
              href="/dokumenty/ZasadyZpracovaniDat-01-07-2020.pdf"
              target="_blank"
            >
              Zásady zpracování osobních údajů
            </a>
            {/* <div style="font-size: 0.8rem;">
              Pokud se změnou nesouhlasíte, kontaktujte nás s žádostí o zrušení
              účtu.
            </div> */}
          </div>
          <br/><br/>

          <h1 style={{textAlign: "center", color: "#000000"}}>Pravidla</h1>
          <p style={{textAlign: "center", color: "#ff0000"}}>
            Hráč registrovaný na serveru <strong>QPlay</strong> souhlasí s těmito
            pravidly a zavazuje se je dodržovat.
          </p>
          <p style={{textAlign: "center", color: "#ff0000"}}>
            Pravidla se vztahují na Minecraft, Discord, TeamSpeak3 a Informační
            panel projektu <b>QPlay.cz</b>.
          </p>
          &nbsp;
          <h3>Podvádění</h3>
          <p>
            Hráč nesmí konat věci, které vedou k jeho obohacení nebo ke škodě
            druhého. Je zakázáno zamlčení podstatné skutečnosti a uvedení hráče v
            omyl.
          </p>

          <h3>Nevhodný skin</h3>
          <p>
            Nevhodný skin obsahuje například prvky nacismu a sexuality. Za skin
            považujeme veškeré jeho prvky včetně například cape.
          </p>

          <h3>Nevhodné jméno</h3>
          <p>
            Nevhodné jméno obsahuje například urážlivé a sexuální prvky, vulgární
            slova. Jméno, které odkazuje na hacky/cheaty je taktéž nevhodné. Jméno
            se nesmí podobat jménu, které používá člen A-týmu.
          </p>

          <h3>Zneužití chyby serveru</h3>
          <p>
            Hráč nesmí zneužívat jakékoliv chyby serveru. Jakmile hráč zjistí
            nějakou chybu na serveru, je povinen ji ihned ohlásit na Informačním
            panelu v ticket-systému. Za nahlášení chyby (je-li první) obdrží
            patřičnou odměnu.
          </p>

          <h3>Povinnosti hráče</h3>
          <p>
            Hráč musí dodržovat platné zákony České republiky.<br/>
            Hráč je povinen na serveru dbát na zásady slušného chování. V případě,
            že zásady slušného chování porušuje jeho spoluhráč/protihráč, měl by
            ho nahlásit A-týmu.<br/>
            Hráč nesmí používat ani vlastnit upravené klienty, které mu ulehčují
            hru v Minecraftu (různé podpůrné nástroje, hacky, double click, multi
            click...). Butterfly click je povolen, avšak je zde vysoké riziko,
            budete blokováni od Anti-Cheatu, proto jeho používání nedoporučujeme.
            Povolené modifikace jsou popsány níže.<br/>
            Hráč nesmí podvádět (žádným způsobem).<br/>
            Hráč nesmí být v jeden okamžik na serveru připojený přes více než 1
            účet za účelem obohacení účtů nebo poškození zájmů projektu QPlay.cz.<br/>
            Je zakázáno si uměle zvyšovat statistiky.<br/>
            Hráč nesmí spamovat chat. Za spam může být považována jakákoliv
            nevhodná zpráva do chatu - reklama, opakování stejné zprávy, nadávky
            apod.<br/>
            Hráč je povinen si chránit svůj účet silným heslem. V případě, že je
            hráč vlastníkem originálního účtu, doporučujeme použít ověření
            účtu.<br/>
            Hráč musí používat pouze vhodné jméno, které není vulgární, neobsahuje
            rasismus.<br/>
            Hráč musí mít nastaven vhodný skin.<br/>
            Hráč musí respektovat všechna nařízení serveru.<br/>
            Hráč nesmí jakýmkoliv způsobem kazit průběh hry ostatním hráčům (cross
            teaming, podkopávání spoluhráčů, targetování druhých hráčů aj.).<br/>
            Hráč nesmí zneužít chyby serveru a musí ji nahlásit A-týmu nebo Vedení
            serveru.<br/>
            Hráč nesmí poskytovat žádné informace o tom, jak obejít systém
            zabezpečení proti podvádění a o způsobech fungování našich ochran.
            Dále nesmí poskytovat informace o instalaci zakázaných cheatů nebo
            komukoliv s instalací (či nastavením) přímo pomoci.<br/>
            Je zakázáno šířit jakékoliv informace o serveru, které nejsou veřejně
            přístupné.<br/>
            Hráč nesmí jakýmkoliv způsobem zneužívat či zbytečně zatěžovat podporu
            serveru. <br/>
            Je zakázáno podporovat nebo propagovat hnutí, které směřuje k
            potlačení práv a svobod člověka nebo hlásá národnostní, rasovou,
            náboženskou či třídní zášť nebo zášť vůči jiné skupině osob.<br/>
            <br/>
            <b>Povolené modifikace:</b><br/>
            1) Veškeré estetické modifikace (například shadery, jas)
            <i>[blinking skin mód je na serveru zakázán]</i><br/>
            2) Veškeré modifikace, které hráče informují, nebo něco indikují
            (například status brnění, status efektů, minimapa, damage indicator)
            <br/>
            3) Módy zlepšující výkon hry nebo zlepšující připojení k serveru
            (například módy zlepšující FPS)<br/>
            <i>Veškeré modifikace jsou používány na vlastní nebezpečí.</i><br/>
          </p>

          <h3>Povinnosti člena A-týmu:</h3>
          <p>
            V případě, že není člen A-týmu AFK, musí hráčům vždy pomoci nebo je
            odkázat na podporu.<br/>
            Člen A-týmu se musí snažit udržovat server v pořádku, je-li někde
            problém, musí zakročit.<br/>
            Člen A-týmu by měl v době své přítomnosti řešit ticket-systém a
            problémy hráčů.<br/>
            Člen A-týmu se nesmí navyšovat nad ostatní hráče.<br/>
            Žádný z členů A-týmu nesmí hráčům poskytovat jakékoliv interní
            informace (například týkající se způsobu fungování Anti-Cheat ochrany,
            informace o poradách AdminTeamu a jiné).
          </p>

          <h3>Respektování hráčů/členů A-týmu</h3>

          <p>
            Je zakázáno komukoliv (hráči nebo A-týmu) jakkoliv vyhrožovat, snažit
            se jej zesměšnit (či jinak znevážit nebo zpochybnit jeho autoritu před
            ostatními hráči), uvádět o něm nepravdivé či nepotvrzené informace.
            Toto pravidlo se týká nejen herního serveru QPlay.cz, ale i
            TeamSpeaku, Discordu a jakýchkoliv veřejně publikovaných
            příspěvků/fotek. Závažnější porušení tohoto pravidla může být
            nahlášeno příslušným úřadům.
          </p>

          <p>
            Hráč:<br/>
            Každý hráč je si roven, a proto musí ostatní hráče na serveru
            respektovat. Vyžadujeme od hráčů, aby při hraní na serveru QPlay dbali
            na zásady slušného chování, byli laskaví a uctiví.<br/>
            Při komunikaci musí hráč brát v potaz, že na serveru hrají i mladší
            hráči, neplnoletí, a proto je nutné komunikovat slušně, bez vulgarit a
            bez sdílení obsahu pro dospělé.<br/>
            Každý má právo na své soukromí, a proto nesmí nikdo na serveru
            sdělovat ostatním hráčům jakékoliv osobní údaje, ani své.<br/>
            Hráč nesmí projevovat žádné prvky provokace, diskriminace, rasismu a
            posměšku.
          </p>

          <p>
            Člen A-týmu:<br/>
            Každé rozhodnutí člena A-týmu je považováno za rozhodující a pokud s
            ním hráč nesouhlasí, musí se obrátit na Vedení A-týmu, které stížnost
            hráče vyřeší.<br/>
            Při řešení problémů je nutné, aby hráč dbal na zásady slušného chování
            a udržel své nervy na uzdě při jakékoliv situaci. Obě strany tak
            předejdou zbytečným komplikacím.
          </p>

          <h3>Trestání</h3>
          <p>
            Hráč:<br/>
            V případě, že hráč obdrží trest neprávem (MC/TS3/Discord), může podat
            ticket s žádostí o unban/unmute na Informační panel a tam se jeho trest
            projedná.<br/>
            Jestliže se hráč snaží mařit nebo obcházet své potrestání, může mu být
            délka trestu navýšena.<br/>
          </p>

          <p>
            Člen A-týmu:<br/>
            Člen A-týmu má právo potrestat hráče, jestliže porušuje jakákoliv
            pravidla serveru.<br/>
            Člen A-týmu musí uchovat důkaz, trvá-li ban déle jak 7 dní. Výjimkou
            jsou bany na 30 a 60 dní. Vedení serveru důkazy uchovávat nemusí.<br/>
          </p>

          <h3>Zabezpečení a sdílení herního účtu</h3>
          <p>
            Je nutné si účet pořádně zabezpečit. K tomu slouží silné heslo a
            ověření originálního Minecraft účtu.<br/>
            Každý hráč je zodpovědný za bezpečnost svého účtu. Pokud jiný uživatel
            získá přístup k Vašemu účtu jakýmikoliv prostředky, stále zodpovídáte
            za svůj účet právě Vy.<br/>
            Sdílet své přihlašovací údaje ostatním hráčům je zakázané. Účet může
            mít pouze jednoho uživatele.<br/>
          </p>
          <p>
            Silné heslo:<br/>
            Silné heslo musí obsahovat kombinaci, která obsahuje velká a malá
            písmena a je doplněna čísly. Silné heslo nesmí být stejné jako herní
            jméno a nemělo by obsahovat slovo.
          </p>

          <h3>Reklama</h3>
          <p>
            Každý hráč, včetně členů A-týmu, nesmí psát do chatu reklamu. Výjimkou
            jsou hráči se skupinou „YouTuber&quot;, kteří mají jiné podmínky stanovené
            vedením serveru.<br/>
            <br/>
            Za reklamu se považuje jakákoliv přímá propagace (IP adresa, pozvánka
            na jiný server aj.) nebo kterákoliv URL adresa, vyjma těch, které souvisí s projektem QPlay.cz. Za reklamu
            se
            nepovažuje reklama na video/YouTube kanál/Twitch kanál tvůrce, který projekt
            QPlay.cz pozitivně propaguje. V případě inzerce názvů svých sociálních
            sítí záleží na posouzení člena A-týmu, zda taková inzerce není
            nevhodná.
            <br/>
            <br/>
            O potrestání reklamy rozhoduje člen A-týmu.
          </p>

          <h3>Obchodování</h3>
          <p>
            Každý hráč, člen A-týmu, Vedení A-týmu a Vedení serveru má zakázáno
            nabízet hráčům v chatu jakoukoliv obchodní nabídku. Předejdeme tak
            několika podvodným dohodám, na které doplatilo v historii Minecraft
            serverů už několik hráčů. Jedná se také o nabídky typu: „Ahoj, pošli
            mi prosím tě určitý počet coins a já ti koupím VIP“.<br/>
            Je zakázáno obchodovat či jen nabízet jakoukoliv obchodní nabídku se
            svým účtem nebo s jeho částmi (coiny, VIP, atd.) nebo s VIP kódy.
          </p>

          <h3>TeamSpeak3</h3>
          <p>
            Každý hráč/uživatel po připojení na TeamSpeak3 je povinen seznámit se
            s pravidly, které nalezne v místnosti [Pravidla TS3]. Pravidla musí
            respektovat.
          </p>

          <h3>Discord</h3>
          <p>
            Každý hráč/uživatel po připojení na Discord je povinen seznámit se s
            pravidly, které nalezne v místnosti [#pravidla]. Pravidla musí
            respektovat.
          </p>

          <h3>Osobní údaje</h3>
          <p>
            Pokud se hráč nebo člen A-týmu jakýmkoliv způsobem dostane k
            jakýmkoliv osobním údajům libovolného hráče (či člena a-týmu), je
            povinen zachovat mlčenlivost a v žádném případě je nesdílet s kýmkoliv
            dalším.
          </p>
          &nbsp; &nbsp;
          <span style={{color: "#000000"}}>
          <i>
            Vyhrazujeme si právo každý případ porušení pravidel posuzovat
            individuálně. Každý registrovaný uživatel na serveru QPlay.cz je
            povinen pravidelně kontrolovat změny těchto pravidel, hraním na
            herním serveru QPlay.cz stvrzuje, že se se všemi pravidly seznámil,
            rozumí jim a zavazuje se je dodržovat. Všechna zde uvedená pravidla
            jsou platná od <strong>06.02.2022</strong>.
          </i>
        </span>
          &nbsp;
        </div>
      </section>
    </div>
  )
}

// pages/pravidla.vue
<template>
  <div>
    <section class="wrapper style1">
      <div class="container">
        <h1 style="text-align: center; color: #000000">
          Všeobecné obchodní podmínky a Podmínky používání služeb QPlay.cz
        </h1>
        <!-- <div style="text-align: center;">
          <a href="/dokumenty/VOP-05-25-2018.pdf" target="_blank">
            Obchodní podmínky (VOP)
          </a>
          <br />
          <a href="/dokumenty/PodminkyPouzivani-05-25-2018.pdf" target="_blank">
            Podmínky používání služeb QPlay.cz
          </a>
          <br />
          <a
            href="/dokumenty/ZasadyZpracovaniDat-05-25-2018.pdf"
            target="_blank"
          >
            Zásady zpracování osobních údajů
          </a>
        </div> -->
        <div style="text-align: center; margin-top: 2em">
          <!-- <h4 style="margin-bottom: 0px;">Platné od 1.7.2020</h4>
          <div>
            Ke dni 1.7. dochází ke změně provozovatele na QPlay Network s.r.o.
          </div> -->
          <a href="/dokumenty/VOP-01-07-2020.pdf" target="_blank">
            Obchodní podmínky (VOP)
          </a>
          <br />
          <a href="/dokumenty/PodminkyPouzivani-01-07-2020.pdf" target="_blank">
            Podmínky používání služeb QPlay.cz
          </a>
          <br />
          <a
            href="/dokumenty/ZasadyZpracovaniDat-01-07-2020.pdf"
            target="_blank"
          >
            Zásady zpracování osobních údajů
          </a>
          <!-- <div style="font-size: 0.8rem;">
            Pokud se změnou nesouhlasíte, kontaktujte nás s žádostí o zrušení
            účtu.
          </div> -->
        </div>
        <br /><br />

        <h1 style="text-align: center; color: #000000">Pravidla</h1>
        <p style="text-align: center; color: #ff0000">
          Hráč registrovaný na serveru <strong>QPlay</strong> souhlasí s těmito
          pravidly a zavazuje se je dodržovat.
        </p>
        <p style="text-align: center; color: #ff0000">
          Pravidla se vztahují na Minecraft, Discord, TeamSpeak3 a Informační
          panel projektu <b>QPlay.cz</b>.
        </p>
        &nbsp;
        <h3>Podvádění</h3>
        <p>
          Hráč nesmí konat věci, které vedou k jeho obohacení nebo ke škodě
          druhého. Je zakázáno zamlčení podstatné skutečnosti a uvedení hráče v
          omyl.
        </p>

        <h3>Nevhodný skin</h3>
        <p>
          Nevhodný skin obsahuje například prvky nacismu a sexuality. Za skin
          považujeme veškeré jeho prvky včetně například cape.
        </p>

        <h3>Nevhodné jméno</h3>
        <p>
          Nevhodné jméno obsahuje například urážlivé a sexuální prvky, vulgární
          slova. Jméno, které odkazuje na hacky/cheaty je taktéž nevhodné. Jméno
          se nesmí podobat jménu, které používá člen A-týmu.
        </p>

        <h3>Zneužití chyby serveru</h3>
        <p>
          Hráč nesmí zneužívat jakékoliv chyby serveru. Jakmile hráč zjistí
          nějakou chybu na serveru, je povinen ji ihned ohlásit na Informačním
          panelu v ticket-systému. Za nahlášení chyby (je-li první) obdrží
          patřičnou odměnu.
        </p>

        <h3>Povinnosti hráče</h3>
        <p>
          Hráč musí dodržovat platné zákony České republiky.<br />
          Hráč je povinen na serveru dbát na zásady slušného chování. V případě,
          že zásady slušného chování porušuje jeho spoluhráč/protihráč, měl by
          ho nahlásit A-týmu.<br />
          Hráč nesmí používat ani vlastnit upravené klienty, které mu ulehčují
          hru v Minecraftu (různé podpůrné nástroje, hacky, double click, multi
          click...). Butterfly click je povolen, avšak je zde vysoké riziko,
          budete blokováni od Anti-Cheatu, proto jeho používání nedoporučujeme.
          Povolené modifikace jsou popsány níže.<br />
          Hráč nesmí podvádět (žádným způsobem).<br />
          Hráč nesmí být v jeden okamžik na serveru připojený přes více než 1
          účet za účelem obohacení účtů nebo poškození zájmů projektu QPlay.cz.<br />
          Je zakázáno si uměle zvyšovat statistiky.<br />
          Hráč nesmí spamovat chat. Za spam může být považována jakákoliv
          nevhodná zpráva do chatu - reklama, opakování stejné zprávy, nadávky
          apod.<br />
          Hráč je povinen si chránit svůj účet silným heslem. V případě, že je
          hráč vlastníkem originálního účtu, doporučujeme použít ověření
          účtu.<br />
          Hráč musí používat pouze vhodné jméno, které není vulgární, neobsahuje
          rasismus.<br />
          Hráč musí mít nastaven vhodný skin.<br />
          Hráč musí respektovat všechna nařízení serveru.<br />
          Hráč nesmí jakýmkoliv způsobem kazit průběh hry ostatním hráčům (cross
          teaming, podkopávání spoluhráčů, targetování druhých hráčů aj.).<br />
          Hráč nesmí zneužít chyby serveru a musí ji nahlásit A-týmu nebo Vedení
          serveru.<br />
          Hráč nesmí poskytovat žádné informace o tom, jak obejít systém
          zabezpečení proti podvádění a o způsobech fungování našich ochran.
          Dále nesmí poskytovat informace o instalaci zakázaných cheatů nebo
          komukoliv s instalací (či nastavením) přímo pomoci.<br />
          Je zakázáno šířit jakékoliv informace o serveru, které nejsou veřejně
          přístupné.<br />
          Hráč nesmí jakýmkoliv způsobem zneužívat či zbytečně zatěžovat podporu
          serveru. <br />
          Je zakázáno podporovat nebo propagovat hnutí, které směřuje k
          potlačení práv a svobod člověka nebo hlásá národnostní, rasovou,
          náboženskou či třídní zášť nebo zášť vůči jiné skupině osob.<br />
          <br />
          <b>Povolené modifikace:</b><br />
          1) Veškeré estetické modifikace (například shadery, jas)
          <i>[blinking skin mód je na serveru zakázán]</i><br />
          2) Veškeré modifikace, které hráče informují, nebo něco indikují
          (například status brnění, status efektů, minimapa, damage indicator)
          <br />
          3) Módy zlepšující výkon hry nebo zlepšující připojení k serveru
          (například módy zlepšující FPS)<br />
          <i>Veškeré modifikace jsou používány na vlastní nebezpečí.</i><br />
        </p>

        <h3>Povinnosti člena A-týmu:</h3>
        <p>
          V případě, že není člen A-týmu AFK, musí hráčům vždy pomoci nebo je
          odkázat na podporu.<br />
          Člen A-týmu se musí snažit udržovat server v pořádku, je-li někde
          problém, musí zakročit.<br />
          Člen A-týmu by měl v době své přítomnosti řešit ticket-systém a
          problémy hráčů.<br />
          Člen A-týmu se nesmí navyšovat nad ostatní hráče.<br />
          Žádný z členů A-týmu nesmí hráčům poskytovat jakékoliv interní
          informace (například týkající se způsobu fungování Anti-Cheat ochrany,
          informace o poradách AdminTeamu a jiné).
        </p>

        <h3>Respektování hráčů/členů A-týmu</h3>

        <p>
          Je zakázáno komukoliv (hráči nebo A-týmu) jakkoliv vyhrožovat, snažit
          se jej zesměšnit (či jinak znevážit nebo zpochybnit jeho autoritu před
          ostatními hráči), uvádět o něm nepravdivé či nepotvrzené informace.
          Toto pravidlo se týká nejen herního serveru QPlay.cz, ale i
          TeamSpeaku, Discordu a jakýchkoliv veřejně publikovaných
          příspěvků/fotek. Závažnější porušení tohoto pravidla může být
          nahlášeno příslušným úřadům.
        </p>

        <p>
          Hráč:<br />
          Každý hráč je si roven, a proto musí ostatní hráče na serveru
          respektovat. Vyžadujeme od hráčů, aby při hraní na serveru QPlay dbali
          na zásady slušného chování, byli laskaví a uctiví.<br />
          Při komunikaci musí hráč brát v potaz, že na serveru hrají i mladší
          hráči, neplnoletí, a proto je nutné komunikovat slušně, bez vulgarit a
          bez sdílení obsahu pro dospělé.<br />
          Každý má právo na své soukromí, a proto nesmí nikdo na serveru
          sdělovat ostatním hráčům jakékoliv osobní údaje, ani své.<br />
          Hráč nesmí projevovat žádné prvky provokace, diskriminace, rasismu a
          posměšku.
        </p>

        <p>
          Člen A-týmu:<br />
          Každé rozhodnutí člena A-týmu je považováno za rozhodující a pokud s
          ním hráč nesouhlasí, musí se obrátit na Vedení A-týmu, které stížnost
          hráče vyřeší.<br />
          Při řešení problémů je nutné, aby hráč dbal na zásady slušného chování
          a udržel své nervy na uzdě při jakékoliv situaci. Obě strany tak
          předejdou zbytečným komplikacím.
        </p>

        <h3>Trestání</h3>
        <p>
          Hráč:<br />
          V případě, že hráč obdrží trest neprávem (MC/TS3/Discord), může podat
          ticket s žádostí o unban/unmute na Informační panel a tam se jeho trest
          projedná.<br />
          Jestliže se hráč snaží mařit nebo obcházet své potrestání, může mu být
          délka trestu navýšena.<br />
        </p>

        <p>
          Člen A-týmu:<br />
          Člen A-týmu má právo potrestat hráče, jestliže porušuje jakákoliv
          pravidla serveru.<br />
          Člen A-týmu musí uchovat důkaz, trvá-li ban déle jak 7 dní. Výjimkou
          jsou bany na 30 a 60 dní. Vedení serveru důkazy uchovávat nemusí.<br />
        </p>

        <h3>Zabezpečení a sdílení herního účtu</h3>
        <p>
          Je nutné si účet pořádně zabezpečit. K tomu slouží silné heslo a
          ověření originálního Minecraft účtu.<br />
          Každý hráč je zodpovědný za bezpečnost svého účtu. Pokud jiný uživatel
          získá přístup k Vašemu účtu jakýmikoliv prostředky, stále zodpovídáte
          za svůj účet právě Vy.<br />
          Sdílet své přihlašovací údaje ostatním hráčům je zakázané. Účet může
          mít pouze jednoho uživatele.<br />
        </p>
        <p>
          Silné heslo:<br />
          Silné heslo musí obsahovat kombinaci, která obsahuje velká a malá
          písmena a je doplněna čísly. Silné heslo nesmí být stejné jako herní
          jméno a nemělo by obsahovat slovo.
        </p>

        <h3>Reklama</h3>
        <p>
          Každý hráč, včetně členů A-týmu, nesmí psát do chatu reklamu. Výjimkou
          jsou hráči se skupinou „YouTuber", kteří mají jiné podmínky stanovené
          vedením serveru.<br />
          <br />
          Za reklamu se považuje jakákoliv přímá propagace (IP adresa, pozvánka
          na jiný server aj.) nebo kterákoliv URL adresa, vyjma těch, které souvisí s projektem QPlay.cz. Za reklamu se
          nepovažuje reklama na video/YouTube kanál/Twitch kanál tvůrce, který projekt
          QPlay.cz pozitivně propaguje. V případě inzerce názvů svých sociálních
          sítí záleží na posouzení člena A-týmu, zda taková inzerce není
          nevhodná.
          <br />
          <br />
          O potrestání reklamy rozhoduje člen A-týmu.
        </p>

        <h3>Obchodování</h3>
        <p>
          Každý hráč, člen A-týmu, Vedení A-týmu a Vedení serveru má zakázáno
          nabízet hráčům v chatu jakoukoliv obchodní nabídku. Předejdeme tak
          několika podvodným dohodám, na které doplatilo v historii Minecraft
          serverů už několik hráčů. Jedná se také o nabídky typu: „Ahoj, pošli
          mi prosím tě určitý počet coins a já ti koupím VIP“.<br />
          Je zakázáno obchodovat či jen nabízet jakoukoliv obchodní nabídku se
          svým účtem nebo s jeho částmi (coiny, VIP, atd.) nebo s VIP kódy.
        </p>

        <h3>TeamSpeak3</h3>
        <p>
          Každý hráč/uživatel po připojení na TeamSpeak3 je povinen seznámit se
          s pravidly, které nalezne v místnosti [Pravidla TS3]. Pravidla musí
          respektovat.
        </p>

        <h3>Discord</h3>
        <p>
          Každý hráč/uživatel po připojení na Discord je povinen seznámit se s
          pravidly, které nalezne v místnosti [#pravidla]. Pravidla musí
          respektovat.
        </p>

        <h3>Osobní údaje</h3>
        <p>
          Pokud se hráč nebo člen A-týmu jakýmkoliv způsobem dostane k
          jakýmkoliv osobním údajům libovolného hráče (či člena a-týmu), je
          povinen zachovat mlčenlivost a v žádném případě je nesdílet s kýmkoliv
          dalším.
        </p>
        &nbsp; &nbsp;
        <span style="color: #000000">
          <i>
            Vyhrazujeme si právo každý případ porušení pravidel posuzovat
            individuálně. Každý registrovaný uživatel na serveru QPlay.cz je
            povinen pravidelně kontrolovat změny těchto pravidel, hraním na
            herním serveru QPlay.cz stvrzuje, že se se všemi pravidly seznámil,
            rozumí jim a zavazuje se je dodržovat. Všechna zde uvedená pravidla
            jsou platná od <strong>06.02.2022</strong>.
          </i>
        </span>
        &nbsp;
      </div>
    </section>
  </div>
</template>
