// pages/yt.vue
<template>
  <div>
    <section class="wrapper style1">
      <div class="container">
        <p style="text-align: center">
          Níže naleznete podmínky a výhody skupiny YouTuber. V případě, že
          podmínky splňujete, tak nás můžete kontaktovat na
          <a href="https://info.qplay.cz/" target="_blank">info.qplay.cz</a>
          vytvořením ticketu s typem "Chci být YouTuber". O&nbsp;konečném
          udělení skupiny YouTuber rozhoduje vedení serveru.
        </p>
        <div
          style="display: flex; flex-wrap: wrap; justify-content: space-around"
        >
          <div>
            <h2>
              Podmínky pro prefix <span style="color: red">YouTuber</span>
            </h2>

            <p>- YouTube kanál musí mít více než 1 500 odběratelů.</p>

            <p>- Počet zhlédnutí na videích musí odpovídat počtu odběratelů.</p>

            <p>- Každé video musí mít převážně více palců nahoru.</p>

            <p>
              - Na YouTube kanále se musí vyskytovat alespoň 2 videa z našeho
              serveru.
            </p>

            <h3>
              Pravidla pro <span style="color: red">YouTubery</span> do 2 000
              odběratelů:
            </h3>

            <p>• Slušně reprezentovat náš server.</p>

            <p>• Dodržovat pravidla našeho serveru.</p>

            <p>• Natáčet každý měsíc alespoň 2 videa z našeho serveru.</p>

            <h3>
              Pravidla pro <span style="color: red">YouTubery</span> do 5 000
              odběratelů:
            </h3>

            <p>• Slušně reprezentovat náš server.</p>

            <p>• Dodržovat pravidla našeho serveru.</p>

            <p>• Natáčet každý měsíc alespoň 1 video z našeho serveru.</p>

            <h3>
              Pravidla pro <span style="color: red">YouTubery</span> do 20 000
              odběratelů:
            </h3>

            <p>• Slušně reprezentovat náš server.</p>

            <p>• Dodržovat pravidla našeho serveru.</p>

            <p>• Natočit za dva měsíce alespoň 1 video z našeho serveru.</p>
          </div>

          <div>
            <h3>
              Pravidla pro <span style="color: red">YouTubery</span> nad 20 000
              odběratelů:
            </h3>

            <p>• Slušně reprezentovat náš server.</p>

            <p>• Dodržovat pravidla našeho serveru.</p>

            <p>• Počet natočených videí z našeho serveru není stanoven.</p>

            <h3>
              Výhody <span style="color: red">YouTubera</span> na serveru:
            </h3>

            <p>1) Prefix YouTuber na Minecraft serveru.</p>

            <p>2) Prefix YouTuber na TS3 serveru.</p>

            <p>3) Má aktivované všechny VIP výhody.</p>

            <p>4) Všechny kity má zadarmo.</p>

            <p>5) Má možnost využít /nick (natáčení videí za skryté jméno).</p>

            <p>6) Může využít možnosti pořádat soutěže s naším serverem.</p>

            <p>7) Jeho kanál je zveřejněn v sekci „Skupiny“ na Info panelu.</p>
            
            <p>8) Skupina YouTuber na <a href="https://discord.qplay.cz" target="_blank">Discord serveru</a> (lze o ni požádat v <a href="https://info.qplay.cz/tickets/new" target="_blank">ticketu</a> s typem "Jiné").</p>

            <br />

            <i>
              * Vyhrazujeme si právo na odebrání
              <span style="color: red">YouTubera</span> bez udání důvodu.
            </i>
          </div>
        </div>
        <!-- <strong>YouTube kanál musí mít více než 1 500 odběratelů a jeho odběratelé musí být aktivní.</strong><br>
Odběratelé se musí přibližně shodovat s počtem zhlédnutí na videu.<br>
Na YouTube kanále se musí vyskytovat minimálně 2 videa z našeho serveru.<br>
<strong>YouTuber nesmí porušovat jakýmkoli způsobem</strong> <strong><a href="?page=pravidla">pravidla serveru QPlay.cz</a>.</strong>
<br><br>
<i>* Vyhrazujeme si právo na odebrání YouTubera bez udání důvodu.<br>
* V případě, že YouTubera osloví samotné Vedení serveru, podmínky pro přijetí budou pozměněny.<br></i> -->
      </div>
    </section>
  </div>
</template>

// pages/yt.tsx
export default function Youtuber() {
  return (
    <div>
      <section className="wrapper style1">
        <div className="container">
          <p style={{textAlign: "center"}}>
            Níže naleznete podmínky a výhody skupiny YouTuber. V případě, že
            podmínky splňujete, tak nás můžete kontaktovat na{" "}
            <a href="https://info.qplay.cz/" target="_blank" rel="noreferrer">info.qplay.cz</a>{" "}
            vytvořením ticketu s typem &quot;Chci být YouTuber&quot;. O&nbsp;konečném
            udělení skupiny YouTuber rozhoduje vedení serveru.
          </p>
          <div
            style={{display: "flex", flexWrap: "wrap", justifyContent: "space-around"}}
          >
            <div>
              <h2>
                Podmínky pro prefix <span style={{color: "red"}}>YouTuber</span>
              </h2>

              <p>- YouTube kanál musí mít více než 1 500 odběratelů.</p>

              <p>- Počet zhlédnutí na videích musí odpovídat počtu odběratelů.</p>

              <p>- Každé video musí mít převážně více palců nahoru.</p>

              <p>
                - Na YouTube kanále se musí vyskytovat alespoň 2 videa z našeho
                serveru.
              </p>

              <h3>
                Pravidla pro <span style={{color: "red"}}>YouTubery</span> do 2 000
                odběratelů:
              </h3>

              <p>• Slušně reprezentovat náš server.</p>

              <p>• Dodržovat pravidla našeho serveru.</p>

              <p>• Natáčet každý měsíc alespoň 2 videa z našeho serveru.</p>

              <h3>
                Pravidla pro <span style={{color: "red"}}>YouTubery</span> do 5 000
                odběratelů:
              </h3>

              <p>• Slušně reprezentovat náš server.</p>

              <p>• Dodržovat pravidla našeho serveru.</p>

              <p>• Natáčet každý měsíc alespoň 1 video z našeho serveru.</p>

              <h3>
                Pravidla pro <span style={{color: "red"}}>YouTubery</span> do 20 000
                odběratelů:
              </h3>

              <p>• Slušně reprezentovat náš server.</p>

              <p>• Dodržovat pravidla našeho serveru.</p>

              <p>• Natočit za dva měsíce alespoň 1 video z našeho serveru.</p>
            </div>

            <div>
              <h3>
                Pravidla pro <span style={{color: "red"}}>YouTubery</span> nad 20 000
                odběratelů:
              </h3>

              <p>• Slušně reprezentovat náš server.</p>

              <p>• Dodržovat pravidla našeho serveru.</p>

              <p>• Počet natočených videí z našeho serveru není stanoven.</p>

              <h3>
                Výhody <span style={{color: "red"}}>YouTubera</span> na serveru:
              </h3>

              <p>1) Prefix YouTuber na Minecraft serveru.</p>

              <p>2) Prefix YouTuber na TS3 serveru.</p>

              <p>3) Má aktivované všechny VIP výhody.</p>

              <p>4) Všechny kity má zadarmo.</p>

              <p>5) Má možnost využít /nick (natáčení videí za skryté jméno).</p>

              <p>6) Může využít možnosti pořádat soutěže s naším serverem.</p>

              <p>7) Jeho kanál je zveřejněn v sekci „Skupiny“ na Info panelu.</p>

              <p>8) Skupina YouTuber na <a href="https://discord.qplay.cz" target="_blank" rel="noreferrer">Discord
                serveru</a> (lze o ni
                požádat v <a href="https://info.qplay.cz/tickets/new" target="_blank" rel="noreferrer">ticketu</a> s
                typem
                &quot;Jiné&quot;).</p>

              <br/>

              <i>
                * Vyhrazujeme si právo na odebrání
                <span style={{color: "red"}}>YouTubera</span> bez udání důvodu.
              </i>
            </div>
          </div>
          {/* <strong>YouTube kanál musí mít více než 1 500 odběratelů a jeho odběratelé musí být aktivní.</strong><br>
Odběratelé se musí přibližně shodovat s počtem zhlédnutí na videu.<br>
Na YouTube kanále se musí vyskytovat minimálně 2 videa z našeho serveru.<br>
<strong>YouTuber nesmí porušovat jakýmkoli způsobem</strong> <strong><a href="?page=pravidla">pravidla serveru QPlay.cz</a>.</strong>
<br><br>
<i>* Vyhrazujeme si právo na odebrání YouTubera bez udání důvodu.<br>
* V případě, že YouTubera osloví samotné Vedení serveru, podmínky pro přijetí budou pozměněny.<br></i> */}
        </div>
      </section>
    </div>
  )
}
