// pages/navod/prihlaseni-bez-hesla.vue
<template>
  <div>
    <section class="wrapper style1">
      <div class="container">
        Máš originální Minecraft a nebaví tě se furt na serveru přihlašovat?
        Vidíš u ostatních hráčů, že mají skin, ale ty ho nemáš? Tak postupuj
        podle tohoto krátkého návodu a aktivuj si tyto výhody i ty! <br />
        <br />
        <ol style="list-style-type: decimal;">
          <li>
            Přihlaš se na stránce
            <a href="https://info.qplay.cz/" target="_blank">
              https://info.qplay.cz
            </a>
          </li>
          <li>
            Na stránce "Domů" najdi položku "Přihlášení na serveru bez hesla"
          </li>
          <li>Klikni na tlačítko "Zapnout"</li>
          <li>Připoj se na server :)</li>
        </ol>
      </div>
    </section>
  </div>
</template>

// pages/navod/prihlaseni-bez-hesla.tsx
export default function LoginWithoutPassword() {
  return (
    <div>
      <section className="wrapper style1">
        <div className="container">
          Máš originální Minecraft a nebaví tě se furt na serveru přihlašovat?
          Vidíš u ostatních hráčů, že mají skin, ale ty ho nemáš? Tak postupuj
          podle tohoto krátkého návodu a aktivuj si tyto výhody i ty! <br/>
          <br/>
          <ol style={{listStyleType: "decimal"}}>
            <li>
              Přihlaš se na stránce{" "}
              <a href="https://info.qplay.cz/" target="_blank" rel="noreferrer">
                https://info.qplay.cz
              </a>
            </li>
            <li>
              Na stránce &quot;Domů&quot; najdi položku &quot;Přihlášení na serveru bez hesla&quot;
            </li>
            <li>Klikni na tlačítko &quot;Zapnout&quot;</li>
            <li>Připoj se na server :)</li>
          </ol>
        </div>
      </section>
    </div>
  )
}
